version: "3"
services: 
    www:
        build: .
        restart: always
        ports: 
            - '8000:80'
        volumes: 
            -  ./:/html
        networks:
            - default
    db:
        image: mysql:8.0.23
        restart: always
        ports: 
            - '3309:3309'
        environment: 
            MYSQL_DATABASE: meudb
            MYSQL_USER: root
            MYSQL_PASSWORD: 
            MYSQL_ROOT_PASSWORD: 
            
volumes: 
    db_data: